# Generated by Django 4.0.4 on 2022-04-11 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости сайта',
            },
        ),
    ]
